export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const ACCESS_TOKEN_ERROR = "ACCESS_TOKEN_ERROR";
export const ACCESS_TOKEN_SUCCESS = "ACCESS_TOKEN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

//PROFILE REDUCER
export const AUTH_USER_LOAD = "AUTH_USER_LOAD";
export const AUTH_USER_LOAD_ERROR = "AUTH_USER_LOAD_ERROR";
export const PROFILE_UPDATE = "PROFILE_UPDATE";
export const PROFILE_UPDATE_ERROR = "PROFILE_UPDATE_ERROR";

// GAME REDUCER
export const GET_GAME_LIST = "GET_GAME_LIST";
export const SELECT_GAME = "SELECT_GAME";
export const CREATE_GAME = "CREATE_GAME";
export const CREATE_GAME_ERROR = "CREATE_GAME_ERROR";

// PLAYER REDUCER
export const GET_PLAYER_DETAILS = "GET_PLAYER_DETAILS";
export const GET_PLAYER_DETAILS_ERROR = "GET_PLAYER_DETAILS_ERROR";
export const GET_PLAYER_LIST = "GET_PLAYER_LIST";
export const CREATE_PLAYER = "CREATE_PLAYER";
export const CREATE_PLAYER_ERROR = "CREATE_PLAYER_ERROR";
export const UPDATE_PLAYER = "UPDATE_PLAYER";
export const UPDATE_PLAYER_ERROR = "UPDATE_PLAYER_ERROR";
export const DELETE_PLAYER = "DELETE_PLAYER";
export const DELETE_PLAYER_ERROR = "DELETE_PLAYER_ERROR";

// TEAM REDUCER
export const GET_TEAM_DETAILS = "GET_TEAM_DETAILS";
export const GET_TEAM_DETAILS_ERROR = "GET_TEAM_DETAILS_ERROR";
export const GET_TEAM_LIST = "GET_TEAM_LIST";
export const CREATE_TEAM = "CREATE_TEAM";
export const CREATE_TEAM_ERROR = "CREATE_TEAM_ERROR";
export const UPDATE_TEAM = "UPDATE_TEAM";
export const UPDATE_TEAM_ERROR = "UPDATE_TEAM_ERROR";
